In [3]:
!pip install scipy 
from scipy import stats
import pandas as pd
import numpy as np


In [ ]:
1.CUTLETS EXERCISE

In [6]:
df=pd.read_csv("Cutlets.csv")
df.head(5)


Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [ ]:
#assuming null hypothesis:ho=>μ1 = μ2
#alternate hypothesis:ha=>μ1 != μ2
#2 sample t test as the population std dev is not given  

In [7]:
stats.ttest_ind(df["Unit A"],df["Unit B"])

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [ ]:
pvalue=0.4722394724599501
significance value=0.05

pvalue>significance value
accepting null hypothesis,μ1 = μ2
the mean of the two samples taken are equal.


In [ ]:
2.LabTAT exercise


In [10]:
df1=pd.read_csv("LabTAT.csv")
df1.head(5)

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [ ]:
#using anova test for more than two samples 
#Assuming nullhypothesis ho:all 4 means are same 
#alternate hypothesis ha:atleast one sample mean is not same

In [11]:
stats.f_oneway(df1.iloc[:,0],df1.iloc[:,1],df1.iloc[:,2],df1.iloc[:,3])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [ ]:
pvalue=2.1156708949992414e-57
significance value=0.05

pvalue<significance value
rejeting the nul hypothesis
#atleast one sample mean is not same


In [ ]:
3.Buyer Ratio excercise
#using chi square test as we are describing the relationship between categorical data for a population
#ho=no relationship between between variabes (independent)
#ha=relationship between variables(dependent) 


In [14]:
df2=pd.read_csv("BuyerRatio.csv")
df2

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [16]:
data=df2.iloc[:,1:5]
data

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [18]:
out=stats.chi2_contingency(data)
out

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [19]:
expectedvalue=out[3]
expectedvalue

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [20]:

rows=len(data.iloc[0:2,0])
columns=len(data.iloc[0,0:4])
dof=(rows-1)*(columns-1)
dof

3

In [22]:

from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(data.values,expectedvalue)])
chi_square_statistic=chi_square[0]+chi_square[1]
chi_square_statistic

1.5152956451130446

In [24]:
pvalue=1-chi2.cdf(chi_square_statistic,3)
pvalue

0.6787446296467897

In [26]:
alpha=0.05
pvalue>alpha

True

In [ ]:
#accepting the null hypothesis ho=no relationship between between variabes (independent)

In [ ]:
4.CustomerOrderForm exercise

In [ ]:
#using chi square test as we are describing the relationship between categorical data for a population
#ho=no relationship between between variabes (independent)
#ha=relationship between variables(dependent) 

In [27]:
df3=pd.read_csv("Costomer+OrderForm.csv")
df3

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [28]:
df3["Phillippines"].value_counts()


Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [29]:
df3["Indonesia"].value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [30]:
df3["Malta"].value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [31]:
df3["India"].value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [32]:
observed=([[271,267,269,280],[29,33,31,20]])
observed

[[271, 267, 269, 280], [29, 33, 31, 20]]

In [36]:
test_statistics,p,dof,expected=stats.chi2_contingency(observed)
test_statistics,p,dof,expected

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [38]:
p

0.2771020991233135

In [39]:
alpha=0.05
p>alpha

True

In [ ]:
#accepting the null hypothesis ho=no relationship between between the variables(independent)