In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.naive_bayes import MultinomialNB 
from sklearn.naive_bayes import GaussianNB 


In [2]:
train_data=pd.read_csv("SalaryData_Train.csv")

In [3]:
test_data=pd.read_csv("SalaryData_Test.csv")

In [4]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            30161 non-null  int64 
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64 
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64 
 10  capitalloss    30161 non-null  int64 
 11  hoursperweek   30161 non-null  int64 
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB


# EDA on train data

In [5]:
train_data.head(5)

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [45]:
train_data.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
Salary           0
dtype: int64

In [6]:
train_data.drop("native",axis=1,inplace=True)

In [7]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
train_data["Salary"]=label_encoder.fit_transform(train_data["Salary"])

In [8]:
train_data1=pd.get_dummies(train_data,columns=["workclass"])

In [9]:
train_data2=pd.get_dummies(train_data1,columns=["education"])

In [10]:
train_data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 34 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   age                          30161 non-null  int64 
 1   educationno                  30161 non-null  int64 
 2   maritalstatus                30161 non-null  object
 3   occupation                   30161 non-null  object
 4   relationship                 30161 non-null  object
 5   race                         30161 non-null  object
 6   sex                          30161 non-null  object
 7   capitalgain                  30161 non-null  int64 
 8   capitalloss                  30161 non-null  int64 
 9   hoursperweek                 30161 non-null  int64 
 10  Salary                       30161 non-null  int32 
 11  workclass_ Federal-gov       30161 non-null  uint8 
 12  workclass_ Local-gov         30161 non-null  uint8 
 13  workclass_ Private           30

In [11]:
train_data3=pd.get_dummies(train_data2,columns=["maritalstatus","occupation","relationship","race","sex"])

In [12]:
train_data3

age  educationno  capitalgain  capitalloss  hoursperweek  Salary  \
0       39           13         2174            0            40       0   
1       50           13            0            0            13       0   
2       38            9            0            0            40       0   
3       53            7            0            0            40       0   
4       28           13            0            0            40       0   
...    ...          ...          ...          ...           ...     ...   
30156   27           12            0            0            38       0   
30157   40            9            0            0            40       1   
30158   58            9            0            0            40       0   
30159   22            9            0            0            20       0   
30160   52            9        15024            0            40       1   

       workclass_ Federal-gov  workclass_ Local-gov  workclass_ Private  \
0                           0                     0                   0   
1                           0                     0                   0   
2                           0                     0                   1   
3                           0                     0                   1   
4                           0                     0                   1   
...                       ...                   ...                 ...   
30156                       0                     0                   1   
30157                       0                     0                   1   
30158                       0                     0                   1   
30159                       0                     0                   1   
30160                       0                     0                   0   

       workclass_ Self-emp-inc  ...  relationship_ Own-child  \
0                            0  ...                        0   
1                            0  ...                        0   
2                            0  ...                        0   
3                            0  ...                        0   
4                            0  ...                        0   
...                        ...  ...                      ...   
30156                        0  ...                        0   
30157                        0  ...                        0   
30158                        0  ...                        0   
30159                        0  ...                        1   
30160                        1  ...                        0   

       relationship_ Unmarried  relationship_ Wife  race_ Amer-Indian-Eskimo  \
0                            0                   0                         0   
1                            0                   0                         0   
2                            0                   0                         0   
3                            0                   0                         0   
4                            0                   1                         0   
...                        ...                 ...                       ...   
30156                        0                   1                         0   
30157                        0                   0                         0   
30158                        1                   0                         0   
30159                        0                   0                         0   
30160                        0                   1                         0   

       race_ Asian-Pac-Islander  race_ Black  race_ Other  race_ White  \
0                             0            0            0            1   
1                             0            0            0            1   
2                             0            0            0            1   
3                             0            1            0            0   
4                             0            1            0            0   
...                         ...

In [13]:
train_data3["salary"]=train_data3["Salary"]
train_data3.drop("Salary",axis=1,inplace=True)

In [14]:
train_data3["salary"].value_counts()

0    22653
1     7508
Name: salary, dtype: int64

# EDA on test data

In [15]:
test_data.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [16]:
test_data.drop("native",axis=1,inplace=True)

In [17]:
test_data1=pd.get_dummies(test_data,columns=["workclass","education"])

In [18]:
test_data2=pd.get_dummies(test_data1,columns=["maritalstatus","occupation","relationship","race","sex"])

In [19]:
test_data2["Salary"]=label_encoder.fit_transform(test_data2["Salary"])

In [20]:
test_data2

age  educationno  capitalgain  capitalloss  hoursperweek  Salary  \
0       25            7            0            0            40       0   
1       38            9            0            0            50       0   
2       28           12            0            0            40       1   
3       44           10         7688            0            40       1   
4       34            6            0            0            30       0   
...    ...          ...          ...          ...           ...     ...   
15055   33           13            0            0            40       0   
15056   39           13            0            0            36       0   
15057   38           13            0            0            50       0   
15058   44           13         5455            0            40       0   
15059   35           13            0            0            60       1   

       workclass_ Federal-gov  workclass_ Local-gov  workclass_ Private  \
0                           0                     0                   1   
1                           0                     0                   1   
2                           0                     1                   0   
3                           0                     0                   1   
4                           0                     0                   1   
...                       ...                   ...                 ...   
15055                       0                     0                   1   
15056                       0                     0                   1   
15057                       0                     0                   1   
15058                       0                     0                   1   
15059                       0                     0                   0   

       workclass_ Self-emp-inc  ...  relationship_ Own-child  \
0                            0  ...                        1   
1                            0  ...                        0   
2                            0  ...                        0   
3                            0  ...                        0   
4                            0  ...                        0   
...                        ...  ...                      ...   
15055                        0  ...                        1   
15056                        0  ...                        0   
15057                        0  ...                        0   
15058                        0  ...                        1   
15059                        1  ...                        0   

       relationship_ Unmarried  relationship_ Wife  race_ Amer-Indian-Eskimo  \
0                            0                   0                         0   
1                            0                   0                         0   
2                            0                   0                         0   
3                            0                   0                         0   
4                            0                   0                         0   
...                        ...                 ...                       ...   
15055                        0                   0                         0   
15056                        0                   0                         0   
15057                        0                   0                         0   
15058                        0                   0                         0   
15059                        0                   0                         0   

       race_ Asian-Pac-Islander  race_ Black  race_ Other  race_ White  \
0                             0            1            0            0   
1                             0            0            0            1   
2                             0            0            0            1   
3                             0            1            0            0   
4                             0            0            0            1   
...                         ...

In [21]:
test_data2["salary"]=test_data2["Salary"]

In [22]:
test_data2.drop("Salary",axis=1,inplace=True)

In [23]:
train_x=train_data3.iloc[:,0:-1]

In [24]:
train_y=train_data3.iloc[:,-1]

In [25]:
test_x=test_data2.iloc[:,0:-1]

In [26]:
test_y=test_data2.iloc[:,-1]

# Multinomial naive bayes

In [27]:
from sklearn.naive_bayes import MultinomialNB

In [28]:
MB=MultinomialNB()

In [29]:
MB.fit(train_x,train_y)

MultinomialNB()

In [30]:
y_pred=MB.predict(test_x)
y_pred

array([0, 0, 0, ..., 0, 1, 0])

In [31]:
from sklearn.metrics import classification_report
print(classification_report(test_y,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.96      0.87     11360
           1       0.62      0.21      0.32      3700

    accuracy                           0.77     15060
   macro avg       0.71      0.58      0.59     15060
weighted avg       0.75      0.77      0.73     15060



In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y,y_pred)

array([[10891,   469],
       [ 2920,   780]], dtype=int64)

# Gaussian naive bayes

In [33]:
from sklearn.naive_bayes import GaussianNB

In [34]:
GB=GaussianNB()

In [35]:
GB.fit(train_x,train_y)

GaussianNB()

In [36]:
y_pred1=GB.predict(test_x)
y_pred1

array([0, 0, 1, ..., 1, 1, 1])

In [37]:
print(classification_report(test_y,y_pred1))

              precision    recall  f1-score   support

           0       0.93      0.81      0.86     11360
           1       0.58      0.81      0.67      3700

    accuracy                           0.81     15060
   macro avg       0.75      0.81      0.77     15060
weighted avg       0.84      0.81      0.82     15060



In [38]:
confusion_matrix(test_y,y_pred1)

array([[9178, 2182],
       [ 719, 2981]], dtype=int64)

In [44]:
multinomial_accuracy=np.mean(test_y==y_pred)*100
multinomial_accuracy

77.49667994687915

In [43]:
gaussian_accuracy=np.mean(test_y==y_pred1)*100
gaussian_accuracy

80.73705179282868

# GAUSSIAN NAIVE BAYES CLASSIFICATION PERFORMS BETTER THAN MULTINOMIAL NAIVE BAYES CLASSIFICATION